//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5456
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 


/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class RTML {
    
    private RTMLContact contactField;
    
    private RTMLRequest[] requestField;
    
    private float versionField;
    
    /// <comentarios/>
    public RTMLContact Contact {
        get {
            return this.contactField;
        }
        set {
            this.contactField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("Request")]
    public RTMLRequest[] Request {
        get {
            return this.requestField;
        }
        set {
            this.requestField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RTMLContact {
    
    private string userField;
    
    private string emailField;
    
    private string organizationField;
    
    /// <comentarios/>
    public string User {
        get {
            return this.userField;
        }
        set {
            this.userField = value;
        }
    }
    
    /// <comentarios/>
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <comentarios/>
    public string Organization {
        get {
            return this.organizationField;
        }
        set {
            this.organizationField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RTMLRequest {
    
    private string idField;
    
    private string userNameField;
    
    private string observersField;
    
    private string descriptionField;
    
    private string reasonField;
    
    private string projectField;
    
    private RTMLRequestSchedule scheduleField;
    
    private string telescopeField;
    
    private System.DateTime timeStampField;
    
    private bool timeStampFieldSpecified;
    
    private RTMLRequestTarget[] targetField;
    
    private RTMLRequestCorrection correctionField;
    
    private bool besteffortsField;
    
    private bool besteffortsFieldSpecified;
    
    /// <comentarios/>
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <comentarios/>
    public string UserName {
        get {
            return this.userNameField;
        }
        set {
            this.userNameField = value;
        }
    }
    
    /// <comentarios/>
    public string Observers {
        get {
            return this.observersField;
        }
        set {
            this.observersField = value;
        }
    }
    
    /// <comentarios/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <comentarios/>
    public string Reason {
        get {
            return this.reasonField;
        }
        set {
            this.reasonField = value;
        }
    }
    
    /// <comentarios/>
    public string Project {
        get {
            return this.projectField;
        }
        set {
            this.projectField = value;
        }
    }
    
    /// <comentarios/>
    public RTMLRequestSchedule Schedule {
        get {
            return this.scheduleField;
        }
        set {
            this.scheduleField = value;
        }
    }
    
    /// <comentarios/>
    public string Telescope {
        get {
            return this.telescopeField;
        }
        set {
            this.telescopeField = value;
        }
    }
    
    /// <comentarios/>
    public System.DateTime TimeStamp {
        get {
            return this.timeStampField;
        }
        set {
            this.timeStampField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TimeStampSpecified {
        get {
            return this.timeStampFieldSpecified;
        }
        set {
            this.timeStampFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("Target")]
    public RTMLRequestTarget[] Target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
    
    /// <comentarios/>
    public RTMLRequestCorrection Correction {
        get {
            return this.correctionField;
        }
        set {
            this.correctionField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool bestefforts {
        get {
            return this.besteffortsField;
        }
        set {
            this.besteffortsField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool besteffortsSpecified {
        get {
            return this.besteffortsFieldSpecified;
        }
        set {
            this.besteffortsFieldSpecified = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RTMLRequestSchedule {
    
    private float extinctField;
    
    private bool extinctFieldSpecified;
    
    private float seeingField;
    
    private bool seeingFieldSpecified;
    
    private float airmassField;
    
    private bool airmassFieldSpecified;
    
    private RTMLRequestScheduleAirmassRange airmassRangeField;
    
    private float horizonField;
    
    private bool horizonFieldSpecified;
    
    private RTMLRequestScheduleHourAngleRange hourAngleRangeField;
    
    private RTMLRequestScheduleSkyCondition skyConditionField;
    
    private bool skyConditionFieldSpecified;
    
    private RTMLRequestScheduleMoon moonField;
    
    private RTMLRequestScheduleTimeRange timeRangeField;
    
    private sbyte priorityField;
    
    private bool priorityFieldSpecified;
    
    /// <comentarios/>
    public float Extinct {
        get {
            return this.extinctField;
        }
        set {
            this.extinctField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ExtinctSpecified {
        get {
            return this.extinctFieldSpecified;
        }
        set {
            this.extinctFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public float Seeing {
        get {
            return this.seeingField;
        }
        set {
            this.seeingField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SeeingSpecified {
        get {
            return this.seeingFieldSpecified;
        }
        set {
            this.seeingFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public float Airmass {
        get {
            return this.airmassField;
        }
        set {
            this.airmassField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AirmassSpecified {
        get {
            return this.airmassFieldSpecified;
        }
        set {
            this.airmassFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public RTMLRequestScheduleAirmassRange AirmassRange {
        get {
            return this.airmassRangeField;
        }
        set {
            this.airmassRangeField = value;
        }
    }
    
    /// <comentarios/>
    public float Horizon {
        get {
            return this.horizonField;
        }
        set {
            this.horizonField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HorizonSpecified {
        get {
            return this.horizonFieldSpecified;
        }
        set {
            this.horizonFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public RTMLRequestScheduleHourAngleRange HourAngleRange {
        get {
            return this.hourAngleRangeField;
        }
        set {
            this.hourAngleRangeField = value;
        }
    }
    
    /// <comentarios/>
    public RTMLRequestScheduleSkyCondition SkyCondition {
        get {
            return this.skyConditionField;
        }
        set {
            this.skyConditionField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SkyConditionSpecified {
        get {
            return this.skyConditionFieldSpecified;
        }
        set {
            this.skyConditionFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public RTMLRequestScheduleMoon Moon {
        get {
            return this.moonField;
        }
        set {
            this.moonField = value;
        }
    }
    
    /// <comentarios/>
    public RTMLRequestScheduleTimeRange TimeRange {
        get {
            return this.timeRangeField;
        }
        set {
            this.timeRangeField = value;
        }
    }
    
    /// <comentarios/>
    public sbyte Priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrioritySpecified {
        get {
            return this.priorityFieldSpecified;
        }
        set {
            this.priorityFieldSpecified = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RTMLRequestScheduleAirmassRange {
    
    private float minimumField;
    
    private float maximumField;
    
    /// <comentarios/>
    public float Minimum {
        get {
            return this.minimumField;
        }
        set {
            this.minimumField = value;
        }
    }
    
    /// <comentarios/>
    public float Maximum {
        get {
            return this.maximumField;
        }
        set {
            this.maximumField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RTMLRequestScheduleHourAngleRange {
    
    private float eastField;
    
    private float westField;
    
    /// <comentarios/>
    public float East {
        get {
            return this.eastField;
        }
        set {
            this.eastField = value;
        }
    }
    
    /// <comentarios/>
    public float West {
        get {
            return this.westField;
        }
        set {
            this.westField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum RTMLRequestScheduleSkyCondition {
    
    /// <comentarios/>
    Excellent,
    
    /// <comentarios/>
    Good,
    
    /// <comentarios/>
    Fair,
    
    /// <comentarios/>
    Poor,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RTMLRequestScheduleMoon {
    
    private float distanceField;
    
    private float widthField;
    
    /// <comentarios/>
    public float Distance {
        get {
            return this.distanceField;
        }
        set {
            this.distanceField = value;
        }
    }
    
    /// <comentarios/>
    public float Width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RTMLRequestScheduleTimeRange {
    
    private System.DateTime earliestField;
    
    private System.DateTime latestField;
    
    /// <comentarios/>
    public System.DateTime Earliest {
        get {
            return this.earliestField;
        }
        set {
            this.earliestField = value;
        }
    }
    
    /// <comentarios/>
    public System.DateTime Latest {
        get {
            return this.latestField;
        }
        set {
            this.latestField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RTMLRequestTarget {
    
    private string idField;
    
    private string nameField;
    
    private string descriptionField;
    
    private RTMLRequestTargetCoordinates coordinatesField;
    
    private string planetField;
    
    private string orbitalElementsField;
    
    private double positionAngleField;
    
    private bool positionAngleFieldSpecified;
    
    private RTMLRequestTargetPicture[] pictureField;
    
    private float timefromprevField;
    
    private bool timefromprevFieldSpecified;
    
    private float tolfromprevField;
    
    private bool tolfromprevFieldSpecified;
    
    private uint countField;
    
    private bool countFieldSpecified;
    
    private float intervalField;
    
    private bool intervalFieldSpecified;
    
    private float toleranceField;
    
    private bool toleranceFieldSpecified;
    
    private bool autofocusField;
    
    private bool autofocusFieldSpecified;
    
    /// <comentarios/>
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <comentarios/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <comentarios/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <comentarios/>
    public RTMLRequestTargetCoordinates Coordinates {
        get {
            return this.coordinatesField;
        }
        set {
            this.coordinatesField = value;
        }
    }
    
    /// <comentarios/>
    public string Planet {
        get {
            return this.planetField;
        }
        set {
            this.planetField = value;
        }
    }
    
    /// <comentarios/>
    public string OrbitalElements {
        get {
            return this.orbitalElementsField;
        }
        set {
            this.orbitalElementsField = value;
        }
    }
    
    /// <comentarios/>
    public double PositionAngle {
        get {
            return this.positionAngleField;
        }
        set {
            this.positionAngleField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PositionAngleSpecified {
        get {
            return this.positionAngleFieldSpecified;
        }
        set {
            this.positionAngleFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("Picture")]
    public RTMLRequestTargetPicture[] Picture {
        get {
            return this.pictureField;
        }
        set {
            this.pictureField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float timefromprev {
        get {
            return this.timefromprevField;
        }
        set {
            this.timefromprevField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool timefromprevSpecified {
        get {
            return this.timefromprevFieldSpecified;
        }
        set {
            this.timefromprevFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float tolfromprev {
        get {
            return this.tolfromprevField;
        }
        set {
            this.tolfromprevField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool tolfromprevSpecified {
        get {
            return this.tolfromprevFieldSpecified;
        }
        set {
            this.tolfromprevFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool countSpecified {
        get {
            return this.countFieldSpecified;
        }
        set {
            this.countFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float interval {
        get {
            return this.intervalField;
        }
        set {
            this.intervalField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool intervalSpecified {
        get {
            return this.intervalFieldSpecified;
        }
        set {
            this.intervalFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float tolerance {
        get {
            return this.toleranceField;
        }
        set {
            this.toleranceField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool toleranceSpecified {
        get {
            return this.toleranceFieldSpecified;
        }
        set {
            this.toleranceFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool autofocus {
        get {
            return this.autofocusField;
        }
        set {
            this.autofocusField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool autofocusSpecified {
        get {
            return this.autofocusFieldSpecified;
        }
        set {
            this.autofocusFieldSpecified = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RTMLRequestTargetCoordinates {
    
    private double rightAscensionField;
    
    private double declinationField;
    
    private System.DateTime dateTimeField;
    
    private bool dateTimeFieldSpecified;
    
    /// <comentarios/>
    public double RightAscension {
        get {
            return this.rightAscensionField;
        }
        set {
            this.rightAscensionField = value;
        }
    }
    
    /// <comentarios/>
    public double Declination {
        get {
            return this.declinationField;
        }
        set {
            this.declinationField = value;
        }
    }
    
    /// <comentarios/>
    public System.DateTime DateTime {
        get {
            return this.dateTimeField;
        }
        set {
            this.dateTimeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DateTimeSpecified {
        get {
            return this.dateTimeFieldSpecified;
        }
        set {
            this.dateTimeFieldSpecified = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RTMLRequestTargetPicture {
    
    private string nameField;
    
    private string descriptionField;
    
    private float exposureTimeField;
    
    private uint binningField;
    
    private bool binningFieldSpecified;
    
    private string filterField;
    
    private float[] itemsField;
    
    private ItemsChoiceType[] itemsElementNameField;
    
    private uint countField;
    
    private bool countFieldSpecified;
    
    private bool autostackField;
    
    private bool autostackFieldSpecified;
    
    /// <comentarios/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <comentarios/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <comentarios/>
    public float ExposureTime {
        get {
            return this.exposureTimeField;
        }
        set {
            this.exposureTimeField = value;
        }
    }
    
    /// <comentarios/>
    public uint Binning {
        get {
            return this.binningField;
        }
        set {
            this.binningField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BinningSpecified {
        get {
            return this.binningFieldSpecified;
        }
        set {
            this.binningFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    public string Filter {
        get {
            return this.filterField;
        }
        set {
            this.filterField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("DecOffset", typeof(float))]
    [System.Xml.Serialization.XmlElementAttribute("Dither", typeof(float))]
    [System.Xml.Serialization.XmlElementAttribute("RaOffset", typeof(float))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public float[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool countSpecified {
        get {
            return this.countFieldSpecified;
        }
        set {
            this.countFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool autostack {
        get {
            return this.autostackField;
        }
        set {
            this.autostackField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool autostackSpecified {
        get {
            return this.autostackFieldSpecified;
        }
        set {
            this.autostackFieldSpecified = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
public enum ItemsChoiceType {
    
    /// <comentarios/>
    DecOffset,
    
    /// <comentarios/>
    Dither,
    
    /// <comentarios/>
    RaOffset,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RTMLRequestCorrection {
    
    private bool crPixField;
    
    private bool crPixFieldSpecified;
    
    private bool darkField;
    
    private bool darkFieldSpecified;
    
    private bool domeField;
    
    private bool domeFieldSpecified;
    
    private bool fixPixField;
    
    private bool fixPixFieldSpecified;
    
    private bool flatField;
    
    private bool flatFieldSpecified;
    
    private bool fringeField;
    
    private bool fringeFieldSpecified;
    
    private bool zeroField;
    
    private bool zeroFieldSpecified;
    
    private string valueField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool crPix {
        get {
            return this.crPixField;
        }
        set {
            this.crPixField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool crPixSpecified {
        get {
            return this.crPixFieldSpecified;
        }
        set {
            this.crPixFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool dark {
        get {
            return this.darkField;
        }
        set {
            this.darkField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool darkSpecified {
        get {
            return this.darkFieldSpecified;
        }
        set {
            this.darkFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool dome {
        get {
            return this.domeField;
        }
        set {
            this.domeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool domeSpecified {
        get {
            return this.domeFieldSpecified;
        }
        set {
            this.domeFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool fixPix {
        get {
            return this.fixPixField;
        }
        set {
            this.fixPixField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fixPixSpecified {
        get {
            return this.fixPixFieldSpecified;
        }
        set {
            this.fixPixFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool flat {
        get {
            return this.flatField;
        }
        set {
            this.flatField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool flatSpecified {
        get {
            return this.flatFieldSpecified;
        }
        set {
            this.flatFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool fringe {
        get {
            return this.fringeField;
        }
        set {
            this.fringeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fringeSpecified {
        get {
            return this.fringeFieldSpecified;
        }
        set {
            this.fringeFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool zero {
        get {
            return this.zeroField;
        }
        set {
            this.zeroField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool zeroSpecified {
        get {
            return this.zeroFieldSpecified;
        }
        set {
            this.zeroFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
